routes/web.php
		Route::post('update_attendances/store', 'AttendanceController@updateAttendanceStore')->name('update_attendances.store');
		Route::post('update_attendances/update', 'AttendanceController@updateAttendanceUpdate')->name('update_attendances.update');
		Route::get('update_attendances/{id}/delete', 'AttendanceController@updateAttendanceDelete')->name('update_attendances.delete');


		Route::get('attendances/page/import', 'AttendanceController@import')->name('attendances.import');
		Route::post('attendances/page/import', 'AttendanceController@importPost')->name('attendances.importPost');

		Route::post('attendance/employee/{id}', 'AttendanceController@employeeAttendance')->name('employee_attendance.post');

		{
			Route::post('office_shift/update', 'OfficeShiftController@update')->name('office_shift.update');
			Route::resource('office_shift', 'OfficeShiftController')->except([
				'destroy', 'update', 'show'
			]);
			Route::get('office_shift/{id}/delete', 'OfficeShiftController@destroy')->name('office_shift.destroy');
			Route::post('office_shift/delete/selected', 'OfficeShiftController@delete_by_selection')->name('mass_delete_office_shifts');
		}
		{
			Route::post('holidays/update', 'HolidayController@update')->name('holidays.update');
			Route::resource('holidays', 'HolidayController')->except([
				'destroy', 'create', 'update'
			]);
			Route::get('holidays/{id}/delete', 'HolidayController@destroy')->name('holidays.destroy');
			Route::post('holidays/delete/selected', 'HolidayController@delete_by_selection')->name('mass_delete_holidays');

			Route::get('holidays/{id}/calendarable', 'HolidayController@calendarableDetails')->name('holidays.calendarable');

		}
		{
			Route::post('leaves/update', 'LeaveController@update')->name('leaves.update');
			Route::resource('leaves', 'LeaveController')->except([
				'destroy', 'create', 'update'
			]);
			Route::get('leaves/{id}/delete', 'LeaveController@destroy')->name('leaves.destroy');
			Route::post('leaves/delete/selected', 'LeaveController@delete_by_selection')->name('mass_delete_leaves');

			Route::get('leaves/{id}/calendarable', 'LeaveController@calendarableDetails')->name('leaves.calendarable');
		}
	});

	Route::prefix('payroll')->group(function ()
	{
		Route::get('list', 'PayrollController@index')->name('payroll.index');
		Route::get('payslip', 'PayrollController@dummy')->name('paySlip.index');

		// Route::get('payslip/{id}', 'PayrollController@paySlip')->name('paySlip.show');
		Route::get('payslip_show', 'PayrollController@paySlip')->name('paySlip.show');

		Route::post('payslip/pay/{id}', 'PayrollController@payEmployee')->name('paySlip.pay');
		Route::post('payslip/payment/bulk', 'PayrollController@payBulk')->name('paySlip.bulk_pay');

		// Route::get('payslip/generate/{id}', 'PayrollController@paySlipGenerate')->name('paySlip.generate');
		Route::get('payslip/generate', 'PayrollController@paySlipGenerate')->name('paySlip.generate');

		Route::get('payment_history', 'PayslipController@index')->name('payment_history.index');
		Route::get('payslip/delete/{payslip}', 'PayslipController@delete')->name('payslip.destroy');
		Route::get('payslip/id/{payslip}', 'PayslipController@show')->name('payslip_details.show');
		Route::get('payslip/pdf/id/{payslip}', 'PayslipController@printPdf')->name('payslip.pdf');

	});

	Route::prefix('recruitment')->group(function ()
	{
		{
			Route::post('job_posts/update', 'JobPostController@update')->name('job_posts.update');
			Route::resource('job_posts', 'JobPostController')->except([
				'destroy', 'create', 'update'
			]);
			Route::get('job_posts/{id}/delete', 'JobPostController@destroy')->name('job_posts.destroy');
			Route::post('job_posts/delete/selected', 'JobPostController@delete_by_selection')->name('mass_delete_job_posts');
		}
		{
			Route::resource('job_candidates', 'JobCandidateController')->except([
				'destroy', 'create', 'update', 'store'
			]);
			Route::get('job_candidates/{id}/delete', 'JobCandidateController@destroy')->name('job_candidates.destroy');
		}
		{
			Route::post('job_interviews/update', 'JobInterviewController@update')->name('job_interviews.update');
			Route::resource('job_interviews', 'JobInterviewController')->except([
				'destroy', 'create', 'update'
			]);
			Route::get('job_interviews/{id}/delete', 'JobInterviewController@destroy')->name('job_interviews.destroy');
		}
		{
			Route::get('cms', 'CmsController@index')->name('cms.index');
			Route::post('cms', 'CmsController@store')->name('cms.store');
		}
	});


	Route::prefix('training')->group(function ()
	{
		{
			Route::post('training_lists/update', 'TrainingListController@update')->name('training_lists.update');
			Route::resource('training_lists', 'TrainingListController')->except([
				'destroy', 'create', 'update'
			]);
			Route::get('training_lists/{id}/delete', 'TrainingListController@destroy')->name('training_lists.destroy');
			Route::post('training_lists/delete/selected', 'TrainingListController@delete_by_selection')->name('mass_delete_training_lists');

			Route::get('training_lists/{id}/calendarable', 'TrainingListController@calendarableDetails')->name('training_lists.calendarable');

		}
		{
			Route::post('trainers/update', 'TrainerController@update')->name('trainers.update');
			Route::resource('trainers', 'TrainerController')->except([
				'destroy', 'create', 'update'
			]);
			Route::get('trainers/{id}/delete', 'TrainerController@destroy')->name('trainers.destroy');
			Route::post('trainers/delete/selected', 'TrainerController@delete_by_selection')->name('mass_delete_trainers');
		}
	});

	Route::prefix('accounting')->group(function ()
	{
		{
			Route::post('accounting_list/update', 'AccountListController@update')->name('accounting_list.update');
			Route::resource('accounting_list', 'AccountListController')->except([
				'destroy', 'create', 'update', 'show'
			]);
			Route::get('accounting_list/{id}/delete', 'AccountListController@destroy')->name('accounting_list.destroy');
			Route::post('accounting_list/delete/selected', 'AccountListController@delete_by_selection')->name('mass_delete_accounting_list');

			Route::get('account_balances', 'AccountListController@accountBalance')->name('account_balances');

		}
		{
			Route::post('payees/update', 'FinancePayeeController@update')->name('payees.update');
			Route::get('payees/{id}/delete', 'FinancePayeeController@destroy')->name('payees.destroy');
			Route::resource('payees', 'FinancePayeeController')->except([
				'create', 'update', 'destroy', 'show']);
		}
		{
			Route::post('payers/update', 'FinancePayerController@update')->name('payers.update');
			Route::get('payers/{id}/delete', 'FinancePayerController@destroy')->name('payers.destroy');
			Route::resource('payers', 'FinancePayerController')->except([
				'create', 'update', 'destroy', 'show']);
		}
		{
			Route::post('deposit/update', 'FinanceDepositController@update')->name('deposit.update');
			Route::resource('deposit', 'FinanceDepositController')->except([
				'destroy', 'create', 'update'
			]);
			Route::get('deposit/{id}/delete', 'FinanceDepositController@destroy')->name('deposit.destroy');
			Route::get('deposit/download', 'FinanceDepositController@download')->name('deposit.download');
			Route::get('deposit/download/{id}', 'FinanceDepositController@download')->name('deposit.downloadFile');
		}
		{
			Route::post('expense/update', 'FinanceExpenseController@update')->name('expense.update');
			Route::resource('expense', 'FinanceExpenseController')->except([
				'destroy', 'create', 'update'
			]);
			Route::get('expense/{id}/delete', 'FinanceExpenseController@destroy')->name('expense.destroy');
			Route::get('expense/download', 'FinanceExpenseController@download')->name('expense.download');
			Route::get('expense/download/{id}', 'FinanceExpenseController@download')->name('expense.downloadFile');
		}

		{
			Route::resource('finance_transfer', 'FinanceTransferController')->except([
				'destroy', 'create', 'update', 'show', 'edit'
			]);
		}

		Route::get('transactions', 'FinanceTransactionsController@index')->name('transactions.index');
		Route::get('transactions/{id}/show', 'FinanceTransactionsController@show')->name('transactions.show');

	});

	{
		Route::post('assets/update', 'AssetController@update')->name('assets.update');
		Route::resource('assets', 'AssetController')->except([
			'destroy', 'create', 'update'
		]);
		Route::get('assets/{id}/delete', 'AssetController@destroy')->name('assets.destroy');
		Route::get('assets/download', 'AssetController@download')->name('assets.download');
		Route::get('assets/download/{id}', 'AssetController@download')->name('assets.downloadFile');
		Route::post('assets/delete/selected', 'AssetController@delete_by_selection')->name('mass_delete_assets');
	}


	Route::post('events/update', 'EventController@update')->name('events.update');
	Route::resource('events', 'EventController')->except([
		'destroy', 'create', 'update'
	]);
	Route::get('events/{id}/delete', 'EventController@destroy')->name('events.destroy');
	Route::post('events/delete/selected', 'EventController@delete_by_selection')->name('mass_delete_events');

	Route::get('events/{id}/calendarable', 'EventController@calendarableDetails')->name('events.calendarable');

	Route::post('meetings/update', 'MeetingController@update')->name('meetings.update');
	Route::resource('meetings', 'MeetingController')->except([
		'destroy', 'create', 'update'
	]);
	Route::get('meetings/{id}/delete', 'MeetingController@destroy')->name('meetings.destroy');
	Route::post('meetings/delete/selected', 'MeetingController@delete_by_selection')->name('mass_delete_meetings');

	Route::get('meetings/{id}/calendarable', 'MeetingController@calendarableDetails')->name('meetings.calendarable');


	
	Route::post('tickets/update', 'SupportTicketController@update')->name('tickets.update');
	Route::resource('tickets', 'SupportTicketController')->except([
		'destroy', 'create', 'update'
	]);

app/JobCandidate.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class JobCandidate extends Model
{
    //
	use Notifiable;
	protected $guarded=[];

	public function AppliedJob(){
		return $this->belongsTo('App\JobPost','job_id','id');
	}

	public function getCreatedAtAttribute($value)
	{
		return Carbon::parse($value)->format(env('Date_Format'));
	}
}

app/Http/Controllers/JobCandidateController.php
<?php

namespace App\Http\Controllers;

use App\JobCandidate;

class JobCandidateController extends Controller {

	//

	public function index()
	{

		$logged_user = auth()->user();
		if ($logged_user->can('view-job_candidate'))
		{
			if (request()->ajax())
			{

				$job_candidates = JobCandidate::with('AppliedJob')->get();


				return datatables()->of($job_candidates)
					->setRowId(function ($row)
					{
						return $row->id;
					})
					->addColumn('job_description', function ($row)
					{
						$title = $row->AppliedJob->job_title;
						return '<h4><a href="' . route('jobs.details', $row->AppliedJob) . '"> ' . $title . '</a></h4>';
					})
					->addColumn('candidate_details', function ($row)
					{
						$candidate_name = $row->full_name;
						$fb = $row->fb_id ?? '';
						$linkedin = $row->linkedin_id ?? '';

						return $candidate_name . '<h6><b> ' . trans('file.FB') . ': </b>' . $fb . '</h6>' . '<h6><b>' . trans('file.Linkedin') . ': </b>' . $linkedin . '</h6>';
					})
					->addColumn('cv', function ($row)
					{
						$cv_path = $row->cv;

						return $cv_path;
					})
					->addColumn('action', function ($data)
					{
						$button = '<button type="button" name="show" id="' . $data->id . '" class="details btn btn-light btn-sm">' . trans('Details') . '</button>';
						$button .= '&nbsp;&nbsp;';
						if (auth()->user()->can('delete-job_candidate'))
						{
							$button .= '<button type="button" name="delete" id="' . $data->id . '" class="delete btn btn-danger btn-sm"><i class="dripicons-trash"></i></button>';
						}

						return $button;
					})
					->rawColumns(['action', 'job_description', 'candidate_details'])
					->make(true);
			}

			return view('recruitment.job_candidate.index');
		}
		return abort('403', __('You are not authorized'));
	}


	public function show($id){

		if(request()->ajax())
		{
			$data = JobCandidate::with('AppliedJob')->findOrFail($id);

			$data['job_title']= $data->AppliedJob->job_title;
			$data['short_description']= $data->AppliedJob->short_description;
			$data['company_name'] = $data->AppliedJob->PostJobEmployer->company_name ?? '';


			return response()->json(['data' => $data]);
		}
	}

	public function destroy($id)
	{
		if(!env('USER_VERIFIED'))
		{
			return response()->json(['error' => 'This feature is disabled for demo!']);
		}
		$logged_user = auth()->user();

		if ($logged_user->can('delete-job_candidate'))
		{
			$data = JobCandidate::findOrFail($id);
			$cv_path = $data->cv;

			if($cv_path)
			{
				$cv_path = public_path('uploads/candidate_cv/' . $cv_path);
				if (file_exists($cv_path))
				{
					unlink($cv_path);
				}
			}

			$data->delete();
			return response()->json(['success' => __('Data is successfully deleted')]);
		}
		return response()->json(['success' => __('You are not authorized')]);
	}
}

resources/views/recruitment/job_candidate/index.blade.php
@extends('layout.main')
@section('content')

    <section>

        <div class="container-fluid"><span id="general_result"></span></div>

        <div class="table-responsive">
            <table id="job_candidate-table" class="table ">
                <thead>
                <tr>
                    <th>{{__('Job Title')}}</th>
                    <th>{{__('Candidate Name')}}</th>
                    <th>{{__('Candidate Email')}}</th>
                    <th>{{trans('file.CV')}}</th>
                    <th>{{trans('file.Status')}}</th>
                    <th>{{__('Apply Date')}}</th>
                    <th class="not-exported">{{trans('file.action')}}</th>
                </tr>
                </thead>

            </table>
        </div>
    </section>


    <div class="modal fade" id="candidate_modal" tabindex="-1" role="dialog" aria-labelledby="basicModal"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">{{__('Candidate Info')}}</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">

                    <div class="row">
                        <div class="col-md-12">

                            <div class="table-responsive">

                                <table class="table  table-bordered">

                                    <tr>
                                        <th>{{__('Job Title')}}</th>
                                        <td id="job_description"></td>
                                    </tr>

                                    <tr>
                                        <th>{{__('Name')}}</th>
                                        <td id="candidate_name"></td>
                                    </tr>

                                    <tr>
                                        <th>{{__('Contact')}}</th>
                                        <td id="candidate_contact"></td>
                                    </tr>
                                    <tr>
                                        <th>{{__('Address')}}</th>
                                        <td id="candidate_address"></td>
                                    </tr>

                                    <tr>
                                        <th>{{trans('file.Status')}}</th>
                                        <td id="status"></td>
                                    </tr>

                                    <tr>
                                        <th>{{__('Cover Letter')}}</th>
                                        <td id="cover_letter"></td>
                                    </tr>

                                    <tr>
                                        <th>{{__('Apply Date')}}</th>
                                        <td id="apply_date"></td>
                                    </tr>


                                </table>

                            </div>

                        </div>
                    </div>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">{{trans('file.Close')}}</button>
            </div>
        </div>
    </div>



    <div id="confirmModal" class="modal fade" role="dialog">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title">{{trans('file.Confirmation')}}</h2>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <h4 align="center">{{__('Are you sure you want to remove this data?')}}</h4>
                </div>
                <div class="modal-footer">
                    <button type="button" name="ok_button" id="ok_button" class="btn btn-danger">{{trans('file.OK')}}'</button>
                    <button type="button" class="close btn-default" data-dismiss="modal">{{trans('file.Cancel')}}</button>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        (function($) {  
            "use strict";

            $(document).ready(function () {

                let table_table = $('#job_candidate-table').DataTable({
                    initComplete: function () {
                        this.api().columns([1]).every(function () {
                            var column = this;
                            var select = $('<select><option value=""></option></select>')
                                .appendTo($(column.footer()).empty())
                                .on('change', function () {
                                    var val = $.fn.dataTable.util.escapeRegex(
                                        $(this).val()
                                    );

                                    column
                                        .search(val ? '^' + val + '$' : '', true, false)
                                        .draw();
                                });

                            column.data().unique().sort().each(function (d, j) {
                                select.append('<option value="' + d + '">' + d + '</option>');
                                $('select').selectpicker('refresh');
                            });
                        });
                    },
                    responsive: true,
                    fixedHeader: {
                        header: true,
                        footer: true
                    },
                    processing: true,
                    serverSide: true,
                    ajax: {
                        url: "{{ route('job_candidates.index') }}",
                    },

                    columns: [

                        {
                            data: 'job_description',
                            name: 'job_description',

                        },
                        {
                            data: 'candidate_details',
                            name: 'candidate_details',
                        },
                        {
                            data: 'email',
                            name: 'email',
                        },
                        {
                            data: 'cv',
                            name: 'cv',
                            render:function (data)
                            {
                                return '<a href={{url('public/uploads/candidate_cv')}}'
                                    +'/'+data +'>'+ 'CV' + '</a>';
                            }
                        },
                        {
                            data: 'status',
                            name: 'status',
                        },
                        {
                            data: 'created_at',
                            name: 'created_at',
                        },
                        {
                            data: 'action',
                            name: 'action',
                            orderable: false
                        }
                    ],


                    "order": [],
                    'language': {
                        'lengthMenu': '_MENU_ {{__("records per page")}}',
                        "info": '{{trans("file.Showing")}} _START_ - _END_ (_TOTAL_)',
                        "search": '{{trans("file.Search")}}',
                        'paginate': {
                            'previous': '{{trans("file.Previous")}}',
                            'next': '{{trans("file.Next")}}'
                        }
                    },
                    'columnDefs': [
                        {
                            "orderable": false,
                            'targets': [0, 6],
                        },

                    ],


                    'select': {style: 'multi', selector: 'td:first-child'},
                    'lengthMenu': [[10, 25, 50, -1], [10, 25, 50, "All"]],
                    dom: '<"row"lfB>rtip',
                    buttons: [
                        {
                            extend: 'pdf',
                            text: '<i title="export to pdf" class="fa fa-file-pdf-o"></i>',
                            exportOptions: {
                                columns: ':visible:Not(.not-exported)',
                                rows: ':visible'
                            },
                        },
                        {
                            extend: 'csv',
                            text: '<i title="export to csv" class="fa fa-file-text-o"></i>',
                            exportOptions: {
                                columns: ':visible:Not(.not-exported)',
                                rows: ':visible'
                            },
                        },
                        {
                            extend: 'print',
                            text: '<i title="print" class="fa fa-print"></i>',
                            exportOptions: {
                                columns: ':visible:Not(.not-exported)',
                                rows: ':visible'
                            },
                        },
                        {
                            extend: 'colvis',
                            text: '<i title="column visibility" class="fa fa-eye"></i>',
                            columns: ':gt(0)'
                        },
                    ],
                });
                new $.fn.dataTable.FixedHeader(table_table);
            });


            $(document).on('click', '.details', function () {

                var id = $(this).attr('id');
                $('#form_result').html('');


                var target = "{{ route('job_candidates.index') }}/"+id;

                $.ajax({
                    url: target,
                    dataType: "json",
                    success: function (result) {

                        $('#job_description').html(result.data.job_title + '<br><h6>' + result.data.short_description + '</h6>' );
                        $('#candidate_name').html(result.data.full_name );
                        $('#candidate_contact').html('Email: '+result.data.email + '<br><h6> Phone: '+ result.data.phone + '<br><h6> Fb: '+ result.data.fb_id + '</h6><h6> Linkedin: '+result.data.linkedin_id+'</h6>');
                        $('#candidate_address').html(result.data.address);
                        $('#apply_date').html(result.data.created_at);
                        $('#status').html(result.data.status);
                        $('#cover_letter').html(result.data.cover_letter);
                        $('#candidate_modal').modal('show');
                        $('.modal-title').text("{{__('Candidate Info')}}");
                    }
                });
            });


            let delete_id;

            $(document).on('click', '.delete', function () {
                delete_id = $(this).attr('id');
                $('#confirmModal').modal('show');
                $('.modal-title').text('{{__('DELETE Record')}}');
                $('#ok_button').text('{{trans('file.OK')}}');

            });



            $('.close').on('click', function () {
                $('#job_candidate-table').DataTable().ajax.reload();
            });

            $('#ok_button').on('click', function () {
                let target = "{{ route('job_candidates.index') }}/" + delete_id + '/delete';
                $.ajax({
                    url: target,
                    beforeSend: function () {
                        $('#ok_button').text('{{trans('file.Deleting...')}}');
                    },
                    success: function (data) {
                        let html = '';
                        if (data.success) {
                            html = '<div class="alert alert-success">' + data.success + '</div>';
                        }
                        if (data.error) {
                            html = '<div class="alert alert-danger">' + data.error + '</div>';
                        }
                        setTimeout(function () {
                            $('#general_result').html(html).slideDown(300).delay(5000).slideUp(300);
                            $('#confirmModal').modal('hide');
                            $('#job_candidate-table').DataTable().ajax.reload();
                        }, 2000);
                    }
                })
            });

        })(jQuery);
    </script>

@endsection