routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Route;


Auth::routes(['register' => false]);


Route::group(['middleware' => ['XSS']], function ()
{
	Route::get('/pdf', function () {
		return view('pdf');
	});

	Route::get('/', 'RouteClosureHandlerController@redirectToLogin')->name('redirectToLogin');
	Route::get('help', 'RouteClosureHandlerController@help')->name('help');

	Route::get('home', 'FrontEnd\HomeController@index')->name('home.front');
	Route::get('about', 'FrontEnd\AboutController@index')->name('about.front');
	Route::get('contact', 'FrontEnd\ContactController@index')->name('contact.front');


	Route::get('jobs', 'FrontEnd\JobController@index')->name('jobs');
	Route::get('jobs/details/{job_post}', 'FrontEnd\JobController@details')->name('jobs.details');
	Route::get('jobs/search/category/{url}', 'FrontEnd\JobController@searchByCategory')->name('jobs.searchByCategory');
	Route::get('jobs/search/job_type/{job_type}', 'FrontEnd\JobController@searchByJobType')->name('jobs.searchByJobType');
	Route::post('jobs/apply/{job}', 'FrontEnd\JobController@applyForJob')->name('jobs.apply');


	Route::get('markAsRead', 'RouteClosureHandlerController@markAsReadNotification')->name('markAsRead');
	Route::get('/all/notifications', 'RouteClosureHandlerController@allNotifications')->name('seeAllNoti');
	Route::get('clearAll', 'RouteClosureHandlerController@clearAll')->name('clearAll');


	Route::get('/profile', 'DashboardController@profile')->name('profile');
	Route::put('/profile/{id}', 'DashboardController@profile_update')->name('profile_update');
	Route::post('/profile/employee/{id}', 'DashboardController@employeeProfileUpdate')->name('employee_profile_update');
	Route::post('/profile/change_password/{id}', 'DashboardController@change_password')->name('change_password');

	Route::get('switch/language/{lang}', 'LocaleController@languageSwitch')->name('language.switch');


	Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'admin']], function ()
	{
		Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
	});

	Route::group(['prefix' => 'employee', 'as' => 'employee.', 'middleware' => ['auth']], function ()
	{
		Route::get('/dashboard', 'DashboardController@employeeDashboard')->name('EmployeeDashboard');
	});

	Route::group(['prefix' => 'client', 'as' => 'client.', 'middleware' => ['auth']], function ()
	{
		Route::get('/dashboard', 'DashboardController@clientDashboard')->name('ClientDashboard');
	});


	Route::get('/users-list', 'AllUserController@index')->name('users-list');
	// Route::get('/user-add', 'AllUserController@add_user_form')->name('add-user');
	Route::post('/user-add', 'AllUserController@add_user_process')->name('add-user');
	Route::get('/user-login-info', 'AllUserController@login_info')->name('login-info');
	Route::get('/user_roles', 'AllUserController@user_roles')->name('user-roles');
	Route::get('/user/edit/{id}', 'AllUserController@edit')->name('edit_user');
	Route::post('/update-user', 'AllUserController@process_update')->name('update-user');
	Route::get('/user/delete/{id}', 'AllUserController@delete_user')->name('delete_user');
	Route::post('/user-mass-delete', 'AllUserController@delete_by_selection')->name('delete_by_selection');
	Route::post('/assign_role/{user}', 'AssignRoleController@update')->name('assign_role');
	Route::post('/mass_assign', 'AssignRoleController@mass_update')->name('mass_assign_role');

	Route::prefix('staff')->group(function ()
	{
		{
			Route::post('employees/update', 'EmployeeController@update')->name('employees.update');
			Route::resource('employees', 'EmployeeController')->except([
				'destroy', 'create', 'update'
			]);
			Route::get('employees/{id}/delete', 'EmployeeController@destroy')->name('employees.destroy');
			Route::post('employees/delete/selected', 'EmployeeController@delete_by_selection')->name('mass_delete_employees');

			Route::get('employees/page/import', 'EmployeeController@import')->name('employees.import');
			Route::post('employees/page/import', 'EmployeeController@importPost')->name('employees.importPost');

			//Irfan
			Route::get('employees/filter', 'EmployeeController@employeesFilter')->name('employees.filter');
			Route::get('employees/pdf/{id}', 'EmployeeController@employeePDF')->name('employees.pdf');

            Route::post('employees/{employee}/pension_update', 'EmployeeController@employeesPensionUpdate')->name('employees.pension_update');
		}

		{
			Route::post('employees/{employee}/infoUpdate', 'EmployeeController@infoUpdate')->name('employees_basicInfo.update');
		}
		{
			Route::get('immigrations', 'EmployeeImmigrationController@index')->name('immigrations.index');
			Route::get('immigrations/{id}/edit', 'EmployeeImmigrationController@edit')->name('immigrations.edit');
			Route::get('immigrations/{employee}', 'EmployeeImmigrationController@show')->name('immigrations.show');
			Route::post('immigrations/update', 'EmployeeImmigrationController@update')->name('immigrations.update');
			Route::post('immigrations/{employee}/store', 'EmployeeImmigrationController@store')->name('immigrations.store');
			Route::get('immigrations/{id}/delete', 'EmployeeImmigrationController@destroy')->name('immigrations.destroy');
			Route::get('immigrations/document/download/{id}', 'EmployeeImmigrationController@download')->name('immigrations_document.download');
		}
		{
			Route::get('contacts', 'EmployeeContactController@index')->name('contacts.index');
			Route::get('contacts/{id}/edit', 'EmployeeContactController@edit')->name('contacts.edit');
			Route::get('contacts/{employee}', 'EmployeeContactController@show')->name('contacts.show');
			Route::post('contacts/update', 'EmployeeContactController@update')->name('contacts.update');
			Route::post('contacts/{employee}/store', 'EmployeeContactController@store')->name('contacts.store');
			Route::get('contacts/{id}/delete', 'EmployeeContactController@destroy')->name('contacts.destroy');
		}
		{
			Route::get('social_profile/{employee}', 'EmployeeSocialProfileController@show')->name('social_profile.show');
			Route::post('social_profile/{employee}/store', 'EmployeeController@storeSocialInfo')->name('social_profile.store');
		}
		{
			Route::post('profile_picture/{employee}/store', 'EmployeeController@storeProfilePicture')->name('profile_picture.store');
		}
		{
			Route::get('documents', 'EmployeeDocumentController@index')->name('documents.index');
			Route::get('documents/{id}/edit', 'EmployeeDocumentController@edit')->name('documents.edit');
			Route::get('documents/{employee}', 'EmployeeDocumentController@show')->name('documents.show');
			Route::post('documents/update', 'EmployeeDocumentController@update')->name('documents.update');
			Route::post('documents/{employee}/store', 'EmployeeDocumentController@store')->name('documents.store');
			Route::get('documents/{id}/delete', 'EmployeeDocumentController@destroy')->name('documents.destroy');
			Route::get('documents/document/download/{id}', 'EmployeeDocumentController@download')->name('documents_document.download');
		}
		{
			Route::get('qualifications', 'EmployeeQualificationController@index')->name('qualifications.index');
			Route::get('qualifications/{id}/edit', 'EmployeeQualificationController@edit')->name('qualifications.edit');
			Route::get('qualifications/{employee}', 'EmployeeQualificationController@show')->name('qualifications.show');
			Route::post('qualifications/update', 'EmployeeQualificationController@update')->name('qualifications.update');
			Route::post('qualifications/{employee}/store', 'EmployeeQualificationController@store')->name('qualifications.store');
			Route::get('qualifications/{id}/delete', 'EmployeeQualificationController@destroy')->name('qualifications.destroy');
		}
		{
			Route::get('work_experience', 'EmployeeWorkExperienceController@index')->name('work_experience.index');
			Route::get('work_experience/{id}/edit', 'EmployeeWorkExperienceController@edit')->name('work_experience.edit');
			Route::get('work_experience/{employee}', 'EmployeeWorkExperienceController@show')->name('work_experience.show');
			Route::post('work_experience/update', 'EmployeeWorkExperienceController@update')->name('work_experience.update');
			Route::post('work_experience/{employee}/store', 'EmployeeWorkExperienceController@store')->name('work_experience.store');
			Route::get('work_experience/{id}/delete', 'EmployeeWorkExperienceController@destroy')->name('work_experience.destroy');
		}
		{
			Route::get('bank_account', 'EmployeeBankAccountController@index')->name('bank_account.index');
			Route::get('bank_account/{id}/edit', 'EmployeeBankAccountController@edit')->name('bank_account.edit');
			Route::get('bank_account/{employee}', 'EmployeeBankAccountController@show')->name('bank_account.show');
			Route::post('bank_account/update', 'EmployeeBankAccountController@update')->name('bank_account.update');
			Route::post('bank_account/{employee}/store', 'EmployeeBankAccountController@store')->name('bank_account.store');
			Route::get('bank_account/{id}/delete', 'EmployeeBankAccountController@destroy')->name('bank_account.destroy');
		}
		{
			Route::post('employees/{employee}/storeSalary', 'EmployeeController@storeSalary')->name('employees_basicSalary.store');
		}
		{
            Route::get('salary_basic', 'SalaryBasicController@index')->name('salary_basic.index');
            Route::get('salary_basic/{employee}', 'SalaryBasicController@show')->name('salary_basic.show');

resources/views/dashboard/admin_dashboard.blade.php
@extends('layout.main')
@section('content')

    <section>
        <div class="container-fluid">
            <div class="d-flex justify-content-between mb-30px">
                <div><h1 class="thin-text">{{trans('file.Welcome')}} {{auth()->user()->username}}</h1></div>
                <div><h4 class="thin-text">{{__('Today is')}} {{now()->englishDayOfWeek}} {{now()->format(env('Date_Format'))}}</h4></div>
            </div>
            <div class="row">
                <div class="col-sm-2">
                    <div class="wrapper count-title text-center">
                        <a href="{{route('employees.index')}}">
                            <div class="name"><strong class="purple-text">{{ trans('file.Employees') }}</strong>
                            </div>
                            <div class="count-number employee-count">{{$employees->count()}}</div>
                        </a>
                    </div>
                </div>

                <!-- Count item widget-->
                <div class="col-sm-2">
                    <div class="wrapper count-title text-center">
                        <a href="{{route('attendances.index')}}">
                            <div class="name"><strong class="orange-text">{{trans('file.Attendance')}}</strong></div>
                            <div class="count-number attendance-count">P:{{$attendance_count}}
                                A:{{$employees->count() - $attendance_count}}</div>
                        </a>
                    </div>
                </div>
                <!-- Count item widget-->
                <div class="col-sm-2">
                    <div class="wrapper count-title text-center">
                        <a href="{{route('leaves.index')}}">
                            <div class="name"><strong class="green-text">{{__('Total Leave')}}</strong></div>
                            <div class="count-number leave-count">{{$leave_count}}</div>
                        </a>
                    </div>
                </div>
                <!-- Count item widget-->
                <div class="col-sm-2">
                    <div class="wrapper count-title text-center">
                        <a href="{{route('expense.index')}}">
                            <div class="name"><strong class="blue-text">{{__('Total Expense')}}</strong></div>
                            <div class="count-number total_expense">{{$total_expense}}</div>
                        </a>
                    </div>
                </div>

                <div class="col-sm-2">
                    <div class="wrapper count-title text-center">
                        <a href="{{route('deposit.index')}}">
                            <div class="name"><strong class="green-text">{{__('Total Deposit')}}</strong></div>
                            <div class="count-number total_deposit">{{$total_deposit}}</div>
                        </a>
                    </div>
                </div>
                <!-- Count item widget-->
                <div class="col-sm-2">
                    <div class="wrapper count-title text-center">
                        <a href="{{route('payment_history.index')}}">
                            <div class="name"><strong class="blue-text">{{__('Total Salaries Paid')}}</strong>
                            </div>
                            <div class="count-number total_salaries_paid">{{$total_salaries_paid}}</div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-8 mt-4">
                    <div class="card mb-0">
                        <div class="card-header d-flex align-items-center">
                            <h4>{{trans('file.Payment')}} --- {{__('Last 6 Months ')}}</h4>
                        </div>
                        <div class="card-body">
                            <canvas id="payment_last_six" data-last_six_month_payment = "{{json_encode($per_month_payment) ?? ''}}" data-months="{{json_encode($per_month) ?? ''}}"  data-label1="{{trans('file.Payment')}}" ></canvas>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 mt-4">
                    <div class="card mb-0">
                        <div class="card-header d-flex justify-content-between align-items-center">
                            <h4>{{__('Employee Department')}}</h4>
                        </div>
                        <div class="pie-chart mb-2">
                            <canvas id="department_chart" data-dept_bgcolor='@json($dept_bgcolor_array)'
                                    data-hover_dept_bgcolor='@json($dept_hover_bgcolor_array)'
                                    data-dept_emp_count='@json($dept_count_array)'
                                    data-dept_label='@json($dept_name_array)' width="100" height="95"></canvas>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 mt-4">
                    <div class="card mb-0">
                        <div class="card-header d-flex justify-content-between align-items-center">
                            <h4>{{__('Employee Designation')}}</h4>
                        </div>
                        <div class="pie-chart mb-2">
                            <canvas id="designation_chart" data-desig_bgcolor='@json($desig_bgcolor_array)'
                                    data-hover_desig_bgcolor='@json($desig_hover_bgcolor_array)'
                                    data-desig_emp_count='@json($desig_count_array)'
                                    data-desig_label='@json($desig_name_array)' width="100" height="95"></canvas>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 mt-4">
                    <div class="card mb-0">
                        <div class="card-header d-flex justify-content-between align-items-center">
                            <h4>{{__('Expense Vs Deposit')}}</h4>
                        </div>
                        <div class="pie-chart mb-2">
                            <canvas id="expense_deposit_chart" data-expense_count='{{$total_expense_raw}}'
                                    data-expense_level="{{trans('Expense')}}"
                                    data-deposit_count='{{$total_deposit_raw}}'
                                    data-deposit_level="{{trans('Deposit')}}" width="100" height="95"></canvas>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 mt-4">
                    <div class="card mb-0">
                        <div class="card-header d-flex justify-content-between align-items-center">
                            <h4>{{__('Project Status')}}</h4>
                        </div>
                        <div class="pie-chart mb-2">
                            <canvas id="project_chart" data-project_status='@json($project_count_array)'
                                    data-project_label='@json($project_name_array)' width="100" height="95"></canvas>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-4 mt-4">
                    <div class="wrapper count-title d-flex">
                        <div class="icon blue-text ml-2 mr-3"><i class="dripicons-volume-medium"></i></div>
                        <a href="{{route('announcements.index')}}">
                            <h3 class="mt-3">{{ count($announcements) }} {{trans('file.Announcement')}}</h3>
                        </a>
                    </div>
                </div>
                <div class="col-4 mt-4">
                    <div class="wrapper count-title d-flex">
                        <div class="icon green-text ml-2 mr-3"><i class="dripicons-ticket"></i></div>
                        <a href="{{route('tickets.index')}}">
                            <h3 class="mt-3">{{$ticket_count}} {{__('Open Ticket')}}</h3>
                        </a>
                    </div>
                </div>
                <div class="col-4 mt-4">
                    <div class="wrapper count-title d-flex">
                        <div class="icon orange-text ml-2 mr-3"><i class="dripicons-briefcase"></i></div>
                        <a href="{{route('projects.index')}}">
                            <h3 class="mt-3">{{$completed_projects}} {{__('Completed Projects')}}</h3>
                        </a>
                    </div>
                </div>
            </div>

            <div class="row">
                @include('calendarable.calendar')
            </div>
        </div>

    </section>
@endsection

resources/views/dashboard/client_dashboard.blade.php
@extends('layout.client')
@section('content')

    <section>

    @include('shared.errors')
    @include('shared.flash_message')

    <!-- Content -->
        <div class="container-fluid">
            <div class="row">

                <div class="col-3 col-md-2 mb-3">
                    <img src={{ URL::to('/uploads/profile_photos')}}/{{$user->profile_photo ?? 'avatar.jpg'}}  width='150'
                         class='rounded-circle'>
                </div>

                <div class="col-9 col-md-10 mb-3">
                    <h4 class="font-weight-bold">{{$client->first_name}}  {{$client->last_name}} <span class="text-muted">({{$user->username}})</span>
                    </h4>
                    <div class="text-muted mb-2">{{trans('file.Company')}}: {{$client->company_name}}</div>
                    <p class="text-muted pb-0-5">{{__('Last Login')}}: {{$user->last_login_date}}</p>

                    <a href="{{route('clientProfile')}}">
                        <button class="btn btn-primary btn-block text-uppercase" id="my_profile"><i
                                    class="ion-person"></i>{{trans('file.Profile')}}</button>
                    </a>
                </div>
            </div>
        </div>

        <div class="container-fluid dashboard-counts">
            <div class="row">

                <div class="col-md-3 mt-3">
                    <div class="wrapper count-title text-center">
                        <div>
                            <a href="{{route('clientInvoicePaid')}}">
                                <div class="name"><strong class="purple-text">{{__('Paid Invoice')}}</strong></div>
                                <div class="count-number award_count">{{$paid_invoice_count}}</div>
                            </a>
                        </div>
                    </div>
                </div>


                <div class="col-md-3 mt-3">
                    <div class="wrapper count-title text-center">
                        <div>
                            <a href="{{route('clientInvoice')}}">
                                <div class="name"><strong class="green-text">{{__('Unpaid Invoice')}}</strong></div>
                                <div class="count-number award_count">{{$unpaid_invoice_count}}</div>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="col-md-3 mt-3">
                    <div class="wrapper count-title text-center">
                        <div>
                            <a href="{{route('clientProjectStatus')}}?status=completed">
                                <div class="name"><strong class="blue-text">{{__('Completed Projects')}}</strong>
                                </div>
                                <div class="count-number award_count">{{$completed_project_count}}</div>
                            </a>
                        </div>
                    </div>
                </div>


                <div class="col-md-3 mt-3">
                    <div class="wrapper count-title text-center">
                        <div>
                            <a href="{{route('clientProjectStatus')}}?status=in_progress">
                                <div class="name"><strong class="orange-text">{{__('In Progress Projects')}}</strong>
                                </div>
                                <div class="count-number award_count">{{$in_progress_project_count}}</div>
                            </a>
                        </div>
                    </div>
                </div>

            </div>

            <div class="row">
                <div class="col-md-6 mt-3">
                    <div class="wrapper count-title text-center">
                        <div class="ion ion-information display-4 text-warning"></div>
                        <div>
                            <a href="{{route('clientInvoicePaid')}}">
                                <div class="name"><strong class="green-text">{{__('Paid Amount')}}</strong></div>
                                <div class="count-number award_count">{{$invoice_paid_amount}}</div>
                            </a>
                        </div>
                    </div>
                </div>


                <div class="col-md-6 mt-3">
                    <div class="wrapper count-title text-center">
                        <div class="ion ion-information display-4 text-warning"></div>
                        <div>
                            <a href="{{route('clientInvoice')}}">
                                <div class="name"><strong class="blue-text">{{__('Due Amount')}}</strong></div>
                                <div class="count-number award_count">{{$invoice_unpaid_amount}}</div>
                            </a>
                        </div>
                    </div>
                </div>


            </div>
        </div>


    </section>

@endsection